"""add_user_invite_token_and_expires

Revision ID: 6d35232726b1
Revises: 2bc6605a13d2
Create Date: 2026-09-21 03:42:03.673063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d35232726b1'
down_revision: Union[str, Sequence[str], None] = '2bc6605a13d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('invite_token', sa.String(), nullable=True))
    op.add_column('user_table', sa.Column('invite_expires_at_utc', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_user_table_invite_token'), 'user_table', ['invite_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_table_invite_token'), table_name='user_table')
    op.drop_column('user_table', 'invite_expires_at_utc')
    op.drop_column('user_table', 'invite_token')
    # ### end Alembic commands ###
