"""init

Revision ID: 8ee2ed45df81
Revises: 
Create Date: 2026-09-12 06:36:59.063798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee2ed45df81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_department_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('academic_program_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('academic_semester_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('app_setting_table',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('course_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('program', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('session', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hash_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_table_email'), 'user_table', ['email'], unique=True)
    op.create_table('assignment_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('deadline_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_table_course_id'), 'assignment_table', ['course_id'], unique=False)
    op.create_table('course_learner_table',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'user_id')
    )
    op.create_table('course_instructor_table',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'user_id')
    )
    op.create_table('refresh_token_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_table_token'), 'refresh_token_table', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_token_table_user_id'), 'refresh_token_table', ['user_id'], unique=False)
    op.create_table('learner_details_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fathers_name', sa.String(), nullable=False),
    sa.Column('mothers_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('learner_id', sa.String(), nullable=False),
    sa.Column('reg_no', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('current_program', sa.String(), nullable=False),
    sa.Column('session', sa.String(), nullable=False),
    sa.Column('semester_session', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('zip', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_learner_details_table_learner_id'), 'learner_details_table', ['learner_id'], unique=False)
    op.create_table('instructor_details_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_instructor_details_table_instructor_id'), 'instructor_details_table', ['instructor_id'], unique=False)
    op.create_table('assignment_attachment_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.String(), nullable=False),
    sa.Column('uploaded_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_attachment_table_assignment_id'), 'assignment_attachment_table', ['assignment_id'], unique=False)
    op.create_table('submission_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('submitted_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('graded_by_id', sa.Integer(), nullable=True),
    sa.Column('graded_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graded_by_id'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['learner_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_table_assignment_id'), 'submission_table', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_submission_table_learner_id'), 'submission_table', ['learner_id'], unique=False)
    op.create_table('submission_activity_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor_name', sa.String(), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_activity_table_submission_id'), 'submission_activity_table', ['submission_id'], unique=False)
    op.create_table('submission_attachment_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.String(), nullable=False),
    sa.Column('uploaded_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submission_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_attachment_table_submission_id'), 'submission_attachment_table', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_attachment_table_submission_id'), table_name='submission_attachment_table')
    op.drop_table('submission_attachment_table')
    op.drop_index(op.f('ix_submission_activity_table_submission_id'), table_name='submission_activity_table')
    op.drop_table('submission_activity_table')
    op.drop_index(op.f('ix_submission_table_learner_id'), table_name='submission_table')
    op.drop_index(op.f('ix_submission_table_assignment_id'), table_name='submission_table')
    op.drop_table('submission_table')
    op.drop_index(op.f('ix_assignment_attachment_table_assignment_id'), table_name='assignment_attachment_table')
    op.drop_table('assignment_attachment_table')
    op.drop_index(op.f('ix_instructor_details_table_instructor_id'), table_name='instructor_details_table')
    op.drop_table('instructor_details_table')
    op.drop_index(op.f('ix_learner_details_table_learner_id'), table_name='learner_details_table')
    op.drop_table('learner_details_table')
    op.drop_index(op.f('ix_refresh_token_table_user_id'), table_name='refresh_token_table')
    op.drop_index(op.f('ix_refresh_token_table_token'), table_name='refresh_token_table')
    op.drop_table('refresh_token_table')
    op.drop_table('course_instructor_table')
    op.drop_table('course_learner_table')
    op.drop_index(op.f('ix_assignment_table_course_id'), table_name='assignment_table')
    op.drop_table('assignment_table')
    op.drop_index(op.f('ix_user_table_email'), table_name='user_table')
    op.drop_table('user_table')
    op.drop_table('course_table')
    op.drop_table('app_setting_table')
    op.drop_table('academic_semester_table')
    op.drop_table('academic_program_table')
    op.drop_table('academic_department_table')
    # ### end Alembic commands ###
