"""add_sessions_and_announcements

Revision ID: bba2c4909bf9
Revises: 8ee2ed45df81
Create Date: 2026-09-13 21:02:58.941287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba2c4909bf9'
down_revision: Union[str, Sequence[str], None] = '8ee2ed45df81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('assignment_table', sa.Column('session_id', sa.Integer(), nullable=True))
    op.add_column('assignment_table', sa.Column('submission_formats', sa.String(), server_default='file_upload', nullable=False))
    op.create_index(op.f('ix_assignment_table_session_id'), 'assignment_table', ['session_id'], unique=False)
    op.create_foreign_key('fk_assignment_table_session_id', 'assignment_table', 'session_table', ['session_id'], ['id'], ondelete='SET NULL')
    op.add_column('course_table', sa.Column('meeting_provider', sa.String(), server_default='', nullable=False))
    op.add_column('course_table', sa.Column('meeting_url', sa.String(), nullable=True))
    op.add_column('course_table', sa.Column('meeting_id', sa.String(), server_default='', nullable=False))
    op.add_column('course_table', sa.Column('meeting_passcode', sa.String(), server_default='', nullable=False))
    op.add_column('course_table', sa.Column('schedule_notes', sa.Text(), server_default='', nullable=False))
    op.add_column('submission_table', sa.Column('private_note', sa.Text(), server_default='', nullable=False))
    op.add_column('submission_table', sa.Column('external_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_table', 'external_url')
    op.drop_column('submission_table', 'private_note')
    op.drop_column('course_table', 'schedule_notes')
    op.drop_column('course_table', 'meeting_passcode')
    op.drop_column('course_table', 'meeting_id')
    op.drop_column('course_table', 'meeting_url')
    op.drop_column('course_table', 'meeting_provider')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'assignment_table', type_='foreignkey')
    op.drop_index(op.f('ix_assignment_table_session_id'), table_name='assignment_table')
    op.drop_column('assignment_table', 'submission_formats')
    op.drop_column('assignment_table', 'session_id')
    # ### end Alembic commands ###
