import type { ProgramType } from "@/types";

export const SETTINGS_TABS = [
    { id: "profile", label: "Profile Information" },
    { id: "security", label: "Security" },
    { id: "notifications", label: "Notifications" },
] as const;

export type SettingsTab = (typeof SETTINGS_TABS)[number]["id"];

export const COUNTRIES = [
    "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina",
    "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados",
    "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina",
    "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia",
    "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia",
    "Comoros", "Congo (Democratic Republic of the)", "Congo (Republic of the)", "Costa Rica",
    "Côte d'Ivoire", "Croatia", "Cuba", "Cyprus", "Czechia", "Denmark", "Djibouti", "Dominica",
    "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea",
    "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia",
    "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana",
    "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland",
    "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo",
    "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya",
    "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives",
    "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia",
    "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia",
    "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria",
    "North Korea", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama",
    "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania",
    "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines",
    "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia",
    "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia",
    "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname",
    "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand",
    "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan",
    "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States",
    "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia",
    "Zimbabwe",
];

export const PROGRAM_TYPES: ProgramType[] = [
    "Professional Track",
    "Foundations",
    "Advanced Mastery",
    "Executive Certificate",
    "Open Workshop",
    "Undergraduate",
    "Postgraduate",
];

export const MAX_AVATAR_SIZE = 2 * 1024 * 1024;

export const TIMEZONES = [
    { label: "UTC (Coordinated Universal Time)", value: "UTC" },
    { label: "America/New_York (Eastern Time - US & Canada)", value: "America/New_York" },
    { label: "America/Chicago (Central Time - US & Canada)", value: "America/Chicago" },
    { label: "America/Denver (Mountain Time - US & Canada)", value: "America/Denver" },
    { label: "America/Los_Angeles (Pacific Time - US & Canada)", value: "America/Los_Angeles" },
    { label: "America/Toronto (Eastern Time - Canada)", value: "America/Toronto" },
    { label: "America/Vancouver (Pacific Time - Canada)", value: "America/Vancouver" },
    { label: "America/Sao_Paulo (Brasilia Time)", value: "America/Sao_Paulo" },
    { label: "Europe/London (Greenwich Mean Time / BST)", value: "Europe/London" },
    { label: "Europe/Paris (Central European Time)", value: "Europe/Paris" },
    { label: "Europe/Berlin (Central European Time)", value: "Europe/Berlin" },
    { label: "Europe/Madrid (Central European Time)", value: "Europe/Madrid" },
    { label: "Europe/Rome (Central European Time)", value: "Europe/Rome" },
    { label: "Europe/Amsterdam (Central European Time)", value: "Europe/Amsterdam" },
    { label: "Europe/Athens (Eastern European Time)", value: "Europe/Athens" },
    { label: "Europe/Helsinki (Eastern European Time)", value: "Europe/Helsinki" },
    { label: "Europe/Dublin (Irish Standard Time)", value: "Europe/Dublin" },
    { label: "Africa/Cairo (Eastern European Time)", value: "Africa/Cairo" },
    { label: "Africa/Johannesburg (South Africa Standard Time)", value: "Africa/Johannesburg" },
    { label: "Africa/Lagos (West Africa Time)", value: "Africa/Lagos" },
    { label: "Africa/Nairobi (East Africa Time)", value: "Africa/Nairobi" },
    { label: "Asia/Dubai (Gulf Standard Time - UAE)", value: "Asia/Dubai" },
    { label: "Asia/Riyadh (Arabia Standard Time - Saudi)", value: "Asia/Riyadh" },
    { label: "Asia/Karachi (Pakistan Standard Time)", value: "Asia/Karachi" },
    { label: "Asia/Kolkata (India Standard Time)", value: "Asia/Kolkata" },
    { label: "Asia/Dhaka (Bangladesh Standard Time, UTC+6)", value: "Asia/Dhaka" },
    { label: "Asia/Bangkok (Indochina Time)", value: "Asia/Bangkok" },
    { label: "Asia/Singapore (Singapore Standard Time)", value: "Asia/Singapore" },
    { label: "Asia/Hong_Kong (Hong Kong Time)", value: "Asia/Hong_Kong" },
    { label: "Asia/Tokyo (Japan Standard Time)", value: "Asia/Tokyo" },
    { label: "Asia/Seoul (Korea Standard Time)", value: "Asia/Seoul" },
    { label: "Australia/Sydney (Australian Eastern Time)", value: "Australia/Sydney" },
    { label: "Australia/Melbourne (Australian Eastern Time)", value: "Australia/Melbourne" },
    { label: "Pacific/Auckland (New Zealand Standard Time)", value: "Pacific/Auckland" },
    { label: "Pacific/Honolulu (Hawaii-Aleutian Time)", value: "Pacific/Honolulu" },
];